#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=display_added action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

$HOME/.config/yabai/create_spaces.sh

yabai -m config external_bar               all:30:0     \
                window_border              on           \
                mouse_follows_focus        off          \
                focus_follows_mouse        off          \
                window_placement           second_child \
                window_topmost             off          \
                window_shadow              float        \
                window_opacity             on           \
                window_opacity_duration    0.0         \
                active_window_opacity      1.0          \
                normal_window_opacity      0.90         \
                window_border_width        2            \
                window_border_radius       11           \
                window_animation_duration  0.0         \
                active_window_border_color 0xffc678dd   \
                normal_window_border_color 0xff2a2f38   \
                insert_feedback_color      0xff9dd274   \
                split_ratio                0.50         \
                auto_balance               off          \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                                                        \
                top_padding                4           \
                bottom_padding             4           \
                left_padding               4           \
                right_padding              4           \
                window_gap                 4

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Vimac|Calculator|Software Update|Dictionary|VLC|System Preferences|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off
yabai -m rule --add app="System Settings" manage=off
yabai -m rule --add app="DeepL" manage=off
yabai -m rule --add app="Docker Desktop" manage=off
yabai -m rule --add app="Notes" manage=off
yabai -m rule --add app="Stats" manage=off
yabai -m rule --add app="Karabiner-Elements" manage=off
yabai -m rule --add app="Todoist" manage=off
yabai -m rule --add app="Postgres" manage=off
yabai -m rule --add app="WebStorm|PhpStorm|IntelliJ" title="^Push|Pull|Preferences" manage=off

# Rules for Applications on spaces
yabai -m rule --add app="^Slack$" space=7
yabai -m rule --add app="^Microsoft Outlook$" space=ˆ7

yabai -m rule --add app="^Signal$" space=8
yabai -m rule --add app="^WhatsApp$" space=8

yabai -m rule --add app="^WebStorm$" space=3
yabai -m rule --add app="^PhpStorm$" space=3
yabai -m rule --add app="^IntelliJ IDEA$" space=3
yabai -m rule --add app="^Xcode$" space=3

yabai -m rule --add app="^Microsoft Teams$" space=4

yabai -m config layout bsp

echo "yabai configuration loaded.."
